---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Make sure we have an 'ansible' group
      when: ansible_os_family == 'Debian' 
      group:
        name: ansible
        state: present
 
    - name: Allow 'ansible' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%ansible'
        line: '%ansible ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
 
    - name: Add sudoers users to ansible group
      user:
        name=sysops
        password="$1$1111$q86agydk.EzAME6d3tnor0"
        groups=ansible
        append=yes
        shell=/bin/bash
        state=present
        createhome=yes
        uid=1040
        generate_ssh_key=yes                   
      tags: adduser

 
    - name: Set up authorized keys for the sysops user
      authorized_key: user=sysops key="{{item}}"
      with_file:
        - /home/mostafa/.ssh/id_rsa.pub 
