---
- name: Freeswitch reload
  become: yes
  command: 'fs_cli -x "fsctl shutdown restart now"'

- name: Freeswitch restart
  become: yes
  service: name=freeswitch state=restarted

- name: Restart systemd-timesyncd
  service: name=systemd-timesyncd state=restarted

- name: restart postgresql
  service: name=postgresql state=restarted
  become: yes
